services:
  backend:
    build: ./backend/
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: